baseurl = "https://naist-se.github.io/"
title = "Software Engineering Laboratory - NAIST"
theme = "hugo-universal-theme"
themesDir = "themes/"
languageCode = "en"
defaultContentLanguage = "en"
defaultContentLanguageInSubdir = true

[languages]

  [languages.ja]
    contentDir = 'content/ja'
    disabled = false
    languageCode = 'ja'
    languageName = '日本語'
    title = 'ソフトウェア工学'
    weight = 1

    [languages.ja.params]
      about_us = "<p>奈良先端科学技術大学院大学</br>先端科学技術研究科 情報科学領域</br>〒630-0192 奈良県生駒市高山町8916-5</p>"
      copyright = "<p> <center> © 2013-2024 奈良先端科学技術大学院大学 情報科学研究科 ソフトウェア工学研究室、無断転載を禁じます。</center></p>"
      [languages.ja.params.testimonials]
        enable = true
        title = "研究スタッフ"
      [languages.ja.params.clients]
        enable = true
        title = "研究室メンバー"
        subtitle = ""
      [languages.ja.params.see_more]
        enable = true
        icon = "far fa-file-alt"
        title = "ソフトウェアは成長する、あなたとともに"
        subtitle = "研究内容がプログラミングと密接に関係するため、プログラミング経験があると研究をスムーズに進めることができます。また、ベクトルや集合、グラフといった数学の基礎的な概念を知っていると役立ちます。"
        link_url = "https://naist-se.github.io/"
        link_text = "Homepage"

    [languages.ja.menu]
      [[languages.ja.menu.main]]
        name = 'ニュース'
        url = '/ja/news'
        weight = 1
      [[languages.ja.menu.main]]
        name = '業績'
        url = "/ja/publish/"
        weight = 2
      [[languages.ja.menu.main]]
        name       = "研究テーマ"
        identifier = "research"
        url        = "/ja/research/"
        weight     = 3
      [[languages.ja.menu.main]]
        name       = "研究室の様子"
        identifier = "life"
        url        = "/ja/life/"
        weight     = 4
      [[languages.ja.menu.main]]
        name       = "アクセス・問い合わせ"
        identifier = "menu.access"
        url        = "/ja/access/"
        weight     = 5
      

    [languages.ja.params.recent_posts]
      enable = true
      title = "最近のニュース"
      subtitle = ""
      hide_summary = true
    
    [languages.ja.params.widgets]
      categories = true
      tags = true
      search = true

  [languages.en]
    contentDir = 'content/en'
    disabled = false
    languageCode = 'en-US'
    languageName = 'English'
    title = 'Software Engineering Laboratory'
    weight = 2

    [languages.en.params]
      about_us = "<p> Nara Institute of Science and Technology <br> Graduate School of Advanced Science and Technology, Division of Information Science<br>630-0192 Takayama-cho 8916-5, Ikoma, Nara, Japan </p>"
      copyright = "<p> <center> © 2013-2024 Software Engineering Laboratory, Graduate School of Information Science, Nara Institute of Science and Technology, All rights reserved.</center></p>"
      [languages.en.params.testimonials]
        enable = true
        title = "Research Staff"
      [languages.en.params.clients]
        enable = true
        title = "Laboratory Members"
        subtitle = ""
      [languages.en.params.see_more]
        enable = true
        icon = "far fa-file-alt"
        title = "Software Grows With You"
        subtitle = "Since the research is closely related to programming, having programming experience can help you progress smoothly. Additionally, knowledge of basic mathematical concepts such as vectors, sets, and graphs will be beneficial."
        link_url = "https://naist-se.github.io/"
        link_text = "Homepage"
    
    [languages.en.menu]
      [[languages.en.menu.main]]
        name = 'News'
        url = '/en/news'
        weight = 1
      [[languages.en.menu.main]]
        name = 'Publications'
        url = "/en/publish/"
        weight = 2
      [[languages.en.menu.main]]
        name       = "Research"
        identifier = "research"
        url        = "/en/research/"
        weight     = 3
      [[languages.en.menu.main]]
        name       = "Research Life"
        identifier = "life"
        url        = "/en/life/"
        weight     = 4
      [[languages.en.menu.main]]
        name       = "Access"
        identifier = "menu.access"
        url        = "/en/access/"
        weight     = 5

    [languages.en.params.recent_posts]
      enable = true
      title = "Recent news"
      subtitle = ""
      hide_summary = true

    [languages.en.params.widgets]
      categories = true
      tags = true
      search = true

[params]
  viewMorePostLink = "/news/"
  author = "SE-lab"
  defaultKeywords = ["selab", "naist", "software engineering"]
  mainSections = ["news"]
  defaultDescription = "Official site for SE-NAIST"
    
  # Social media
  facebook_site = "https://www.facebook.com/selabnaist/" # the Facebook handle of your site ('https://www.facebook.com/HANDLE')
  twitter_site = "https://twitter.com/naistselab" # the Twitter handle of your site (without the '@')
  default_sharing_image = "img/graduation-m2-2022-03.png"

  # Google Maps widget: If `googleMapsApiKey` is not set, no key will be passed to Google (which likely results in a broken map widget).
  enableGoogleMaps = true
  googleMapsApiKey = "AIzaSyAv7Sza8NSp9_l_g8G2vlo0H4ydEPn_2jY"
  latitude = "-12.043333"
  longitude = "-77.028333"
  style = "blue"
  date_format = "January 2, 2006"
  dropdown_mouse_over = false
  disabled_logo = false
  logo_text = "SE Lab"
  logo = "img/logo1.png"
  logo_small = "img/logo.png"
  access = "/access"

  [params.carouselCustomers]
    items = 1
    auto_play = true
    slide_speed = 2000
    pagination_speed = 1000

  [params.carouselTestimonials]
    items = 3
    auto_play = true
    slide_speed = 2000
    pagination_speed = 1000

  [params.carouselHomepage]
    enable = true
    auto_play = true
    slide_speed = 2000
    pagination_speed = 1000

  [params.footer.recent_posts]
    enable = false

[permalinks]
  news = "/news/:year/:month/:day/:filename/"

[server]
  [[server.headers]]
    for = "/*"
    [server.headers.values]
      Access-Control-Allow-Origin = "*"
